version: '3.7'

services:
  php-apache:
    container_name: my-php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80  
    networks:
      - lan-networks

  db:
    container_name: mi-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: usuario1
      MYSQL_PASSWORD: pass1234
    volumes:
      - ./mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"

    networks:
      - lan-networks

  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    networks:
      - lan-networks
    ports:
      - 8000:80
    environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
volumes:
  mysql-data:
networks:
  lan-networks: